### ISSUE TITLE
ldap filter (uid=foo) is forced

### ISSUE THREAD

**Issue by Tazoeur** [Maks3w/FR3DLdapBundle#120]
For any configuration I make, the (uid=foo) ldap filter is adding himself to the final request. (foo is the username field from fosuserBundle:security:login.html.twig)

(I'm using` fr3d/ldap-bundle 3.0` and `friendsofsymfony/user-bundle  dev-mater  e770bfa`)

I can see the request in profiler : 
`ldap_driver	{action}({base_dn}, {filter}, {attributes})`
`Context: { "action": "ldap_search", "base_dn": "OU=<w>,DC=<x>,DC=<y>,DC=<z>", "filter": "(&(ObjectClass=person)(uid=foo))", "attributes":[]}`

with the exception
`ldap_driver	{exception}`
`Context: { "exception": "Object(Zend\\Ldap\\Exception\\LdapException)" }`

my config.yml :
```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class : UserBundle\Entity\User

fr3d_ldap:
    driver:
        host: 10.121.137.30
        port: 389
    user:
        baseDn: OU=<w>,DC=<x>,DC=<y>,DC=<z>
        filter: (ObjectClass=person)
        attributes:
            - { ldap_attr: samaccountname,  user_method: setUsername }
            - { ldap_attr: sn, user_method: setName }
            - { ldap_attr: mail, user_method: setEmail }
```

Is it possible to change the (uid=foo) to (samaccountname=foo) in the ldap_search action?

(I hope I'm in the right place to ask about it)
