### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by Dragnucs** [Maks3w/FR3DLdapBundle#123]
I cannot seem to correctly configure this bundle. When I think I get it set correctly I always get an `Invalid credentials` error. If I voluntarily introduce an error some where, then I get a real error.

My setup:
- Symfony 3.0.3
- FOSUserBundle
- FR3DLdapBundle
- SLAPD locally for development
- ActiveDirectory in prod (not an issue for now, I only need to set the project to work with LDAP for the moment)

My config:
```yaml
# security.yml
security:
    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js|fonts|plugins|bundles)/
            security: false
        main:
            pattern: ^/
            fr3d_ldap: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    true
```

```yaml
# config.yml
fr3d_ldap:
    driver:
        host: 127.0.0.1
        username: CN=admin,DC=domain,DC=dev
        password: "p4$$w0rd"
        bindRequiresDn: true
        accountDomainName: domain.dev
        accountDomainNameShort: DOMAIN
    user:
        baseDn: OU=Users,OU=City,OU=Country,DC=domain,DC=dev
        filter: (objectClass=person)
        usernameAttribute: uid
        attributes:
            - { ldap_attr: uid, user_method: setUsername }
            - { ldap_attr: mail, user_method: setEmail }
```

For data, in LDAP I have users' passwords encrypted with SSHA (default) and set one to plaintext.
I tried some different encoders in the `security.yml` like plaintext, ssha, sha512 while connecting both users with encrypted passwords and the plaintext one with no success.

I don't have anything special or fancy in my user management; just a regular most simple FOSUserBundle setup.

How should I set my SLAPD and/or FR3DLdapBundle?

**EDIT:**
Both SLAPD and Symfony logs inform that they found the user, but in Symfony log there is a clear message that the authentification failed:
```
[2016-03-01 11:30:37] security.INFO: User {username} {result} on LDAP {"action":"loadUserByUsername","username":"obenjel","result":"found"} []
[2016-03-01 11:30:37] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /project/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:90, Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at /project/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:67)"} []
[2016-03-01 11:30:37] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/login"} []
```
