### ISSUE TITLE
 jpegPhoto doesn't trigger desired accessor

### ISSUE THREAD

**Issue by Dragnucs** [Maks3w/FR3DLdapBundle#124]
If I set my config.yml like this:
```yaml
fr3d_ldap:
    user:
        attributes:
            - { ldap_attr: jpegPhoto, user_method: setJpegPhoto }
```
Then `setJpegPhoto()` method is never called. Other methods are called just fine.
