### ISSUE TITLE
invalide Credential ?  ldap_driver.DEBUG: {exception} {"exception":

### ISSUE THREAD

**Issue by ychoucha** [Maks3w/FR3DLdapBundle#131]
Hello, 
well i m looking how connect to my ldap, but i found only this erro : 

```
[2016-06-20 18:41:31] ldap_driver.DEBUG: {exception} {"exception":"[object] (Zend\\Ldap\\Exception\\LdapException(code: 49): 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1): user001 at /var/www/user33/Symfony/vendor/zendframework/zend-ldap/src/Ldap.php:842)"} []
```

how fix this error please ?

**Comment by Maks3w** [comment]
Please do your "how to" questions on a Q&A site like stackoverflow.

**Comment by ychoucha** [comment]
Hello i m sill looking a solution but nothing works !

i m sure about my login and password i used.

is about the login and passord on the config.yml.

i thing th way tha'ts FR3DLdapBundle send the password is not correct but i don''t know where looking.

well i m stil searching

web : 
Ldap error signification :
http://ldapwiki.willeke.com/wiki/Common%20Active%20Directory%20Bind%20Errors

**Comment by ychoucha** [comment]
OK i found the problem :+1:  
i have to add in my config.yml files :

missing : 
```
        usernameAttribute: sAMAccountName
```

```
...
fr3d_ldap:
    driver:
       host:     XX.XX.XX.XX
       username: user@domaine.com
       password: password3
       accountDomainName: domaine.com
       accountDomainNameShort: DOMA
    user:
        baseDn: Ou=ListingUsers,DC=domaine,DC=com
        usernameAttribute: sAMAccountName
        filter: (&(ObjectClass=Person))
        attributes:
            - { ldap_attr: samaccountname,  user_method: setUsername }    

```

this information is not on the cookbook


so now i have a new mysql problem 

thanks
