### ISSUE TITLE
Error when installing the bundle

### ISSUE THREAD

**Issue by SahnounM91** [Maks3w/FR3DLdapBundle#141]
I followed the instructions to install FR3DLdapBundle but I got an error and I didn't understand it  : 
`Type error: Argument 2 passed to FR3D\LdapBundle\Driver\ZendLdapDriver::__construct() must be an instance of Symfony\Component\HttpKernel\Log\LoggerInterface, instance of Symfony\Bridge\Monolog\Logger given, called in /home/sahnoun/InternshipPFE/Dev/systeme_evaluation/var/cache/dev/appDevDebugProjectContainer.php on line 2072`

this my security file : 

```
`security:
    erase_credentials: false
    encoders:
        EvalBundle\Entity\Collaborator: bcrypt
    providers:
        in_memory:
            memory: ~
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager 
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true
            // activate different ways to authenticate

            //http_basic: ~

            form_login: ~
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }`
```

and this my configuration : 

```
` imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@EvalBundle/Resources/config/services.yml" }

parameters:
    locale: en
framework:
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    translator: ~

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        mapping_types:
            enum: string


   

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: EvalBundle\Entity\Collaborator
    from_email:
        address: sahnoun.mabrouk@gmail.com
        sender_name: sahnoun MABROUK
fr3d_ldap:
    driver:
        host: myhost
        port: 389    # Optional
        username: username
        password: password       

    user:
        baseDn: sn=users, dc=uib, dc=dev
        filter: (&(ObjectClass=Person))
easy_admin:
    entities:
        - EvalBundle\Entity\Family
        - EvalBundle\Entity\Profession` 
```

can any one help?
