### ISSUE TITLE
Connect fails when useSsl is enabled for a host with a non-standard ldaps port

### ISSUE THREAD

**Issue by baileyp** [Maks3w/FR3DLdapBundle#16]
Per the documentation for [ldap_connect()] [ldap_connect], the `$port` argument is ignored when the `$hostname` is a url.

So, given the following configuration

```yaml
fr3d_ldap:
    client:
        host:     "some.ldap.host"
        port:     1636 #or anything other than the default 636
        useSsl:   true
```

Per [Driver/LdapConnection.php] [driver], the resulting execution basically looks like this

```php
ldap_connect('ldaps://some.ldap.host', 1636);
```

When it actually needs to look like this

```php
ldap_connect('ldaps://some.ldap.host:1636');
```

You can work around this issue in the configuration like so

```yaml
fr3d_ldap:
    client:
        host:     "some.ldap.host:1636"
        port:     ~
        useSsl:   true
```

But I think it would be preferable if the bundle abstracted this little detail away, and added the port to the host when `useSsl` is enabled. Something along the lines of:

```php
    private function connect()
    {
        $host = $this->params['host'];
        if (isset($this->params['useSsl']) && (boolean) $this->params['useSsl']) {
            $host = sprintf('ldaps://%s:%s', $host, $this->params['port'] ?: '636');
        }
       // ...
    }
```

To the best of my knowledge, this effects all versions/branches.

[ldap_connect]: http://php.net/ldap_connect
[driver]: https://github.com/Maks3w/FR3DLdapBundle/blob/master/Driver/LdapConnection.php
