### ISSUE TITLE
Problem php composer.phar update with Symfony2.1 and Ldap-fr3d 1.6

### ISSUE THREAD

**Issue by ghost** [Maks3w/FR3DLdapBundle#32]
I try to update to FR3DLdapBundle. I follow instructions in docs like that :
it's my composer.json

``` yaml
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.1.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.1.*",
        "twig/extensions": "1.0.*@dev",
        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.1.*",
        "symfony/monolog-bundle": "2.1.*",
        "sensio/distribution-bundle": "2.1.*",
        "sensio/framework-extra-bundle": "2.1.*",
        "sensio/generator-bundle": "2.1.*",
        "jms/security-extra-bundle": "1.2.*",
        "jms/di-extra-bundle": "1.1.*",
        "kriswallsmith/assetic": "1.1.*@dev",
        "winzou/console-bundle": "dev-master",
        "twig/extensions": "dev-master",
        "psliwa/pdf-bundle": "dev-master",
        "symfony/class-loader": "2.1.*@dev",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
    "doctrine/data-fixtures": "dev-master",
        "os/excel-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "liuggio/excelbundle": ">=1.0.4",
        "imag/ldap-bundle": "dev-master",
        "opensky/ldap-bundle": "dev-master",
        "fr3d/ldap-bundle": "1.6.*"            },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },"minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web"
    }
}
```

When i update with command : php composer.phar update
I've an exception error like Problem 1 :  "fr3d/ldap-bundle": "1.6._" requires ext-ldap : \* ; ext-ldap is missing from your system.
I don't understand this error because i use wamp server and i untick commentary for php_ldap in php.ini.
Maybe i forget to add "ext-ldap": "_" in composer.json ? But ext-ldap isn't a package, i think. How to use it please ? 

R. Marecat
