### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by thaasch** [Maks3w/FR3DLdapBundle#72]
Hi I started to use your Bundle a few Days ago and had alot of truble to make it work for my ldap server.
The Problem was a \ in the username. All users musst login with HOSTNAME\user. After alot of debuging i found the setting for accountCanonicalForm, accountDomainName and accountDomainNameShort.

It would be great if you could describe these settings in your documentation.

Here is my full config.yml ldap config (with changed ip and password):

``` yml
fr3d_ldap:
    driver:
        host:         127.0.0.1
        port:         389
        username:     'HOSTNAME\backup'
        password:     passwd
        baseDn:       cn=Users,dc=hostname,dc=intern
        accountCanonicalForm: 3
        accountDomainName: HOSTNAME
        accountDomainNameShort: HOSTNAME
    user:
        baseDn: cn=Users,dc=hostname,dc=intern
        filter: (ObjectClass=person)
        attributes:
            - { ldap_attr: samaccountname,  user_method: setUsername }
            - { ldap_attr: mail,  user_method: setEmail }
```
