### ISSUE TITLE
Binding requires username in DN form

### ISSUE THREAD

**Issue by hoangthienan** [Maks3w/FR3DLdapBundle#74]
I'm using FR3DLdapBundle with FOSUserBundle.

> Symfony 2.5.6
> FOSUserBundle ~2.0@dev
> FR3DLdapBundle ~2.0@dev

$ldapManager = $this->get('fr3d_ldap.ldap_manager');
print_r($ldapManager->findUserByUsername('nhoang@ldap.example.com'));

But I catch one error.

> Binding requires username in DN form 
> CRITICAL - Uncaught PHP Exception FR3D\LdapBundle\Driver\LdapDriverException: "An error occur with the search operation." at myproj\vendor\fr3d\ldap-bundle\FR3D\LdapBundle\Driver\ZendLdapDriver.php line 55 

I have done everything in the installation documents

``` yaml
# config.yml
fr3d_ldap:
    driver:
        host:                ldap.example.com
        port:                389
        username:            ldapadmin@ldap.example.com
        password:            password
        bindRequiresDn:      true
        baseDn:              dc=ldap,dc=example,dc=com
        accountFilterFormat: (&(uid=%s)) # Optional. sprintf format %s will be the username
    user:
        baseDn: dc=ldap,dc=example,dc=com
        filter: (&(ObjectClass=Person))
        attributes:
          - { ldap_attr: uid,  user_method: setUsername }
```
