### ISSUE TITLE
Username is empty

### ISSUE THREAD

**Issue by shakastar** [Maks3w/FR3DLdapBundle#77]
Hello,

Thank you for your help here. I followed the instruction and installed this bundle, but I always got a exception that shows username is null. Do you have any idea about this error ? 

> NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO sfcompliance.user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, 1, "dp0nfvfj92osc4cg8gs4g4sww0wsccw", "", "2015-01-07 21:23:34", 0, 0, null, null, null, "a:0:{}", 0, null]:

In the log, I found that
> [2015-01-07 21:23:33] ldap_driver.DEBUG: ldap_search(dc=domain,dc=com, (&(sAMAccountName=shakastar)), sAMAccountName) [] []
> [2015-01-07 21:23:33] security.INFO: User shakastar found on ldap [] []
> [2015-01-07 21:23:33] ldap_driver.DEBUG: ldap_bind(cn=shakastar,ou=Users, ****) [] []
> [2015-01-07 21:23:34] security.INFO: User "" has been authenticated successfully [] []

the username lost at this line (line 73). Do I get something wrong in the configuration ?
```
namespace Symfony\Component\Security\Core\Authentication;
......
class AuthenticationProviderManager implements AuthenticationManagerInterface
......
$result = $provider->authenticate($token);
```

There is security.yml
```
security:
    encoders:
        System\SecurityBundle\Entity\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

    firewalls:
        login_firewall:
           pattern:  ^/login$
           security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: system_cover
            logout:
                path:   logout
                target: login
            fr3d_ldap: ~

    access_control:
        - { path: ^/login&, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
```

And there is config.yml
```
fr3d_ldap:
    driver:
        host: ldap.foo.com
        port: 10077 
        username: CN=ACC,dc=domain,dc=com
        password: PINNUM
    user:
        baseDn: dc=domain,dc=com 
        attributes: # Specify ldap attributes mapping [ldap attribute, user object method]
            - { ldap_attr: sAMAccountName, user_method: setUsername } # Default
```

Thank you for the advice !
